#!/bin/bash
# Program 4: OTP
# File: compileall
# Author: Clare Brown
# ONID: browncla
# Date: 12/1/16
# Description: File to make sure there are no strange characters in the plaintext 
# files and to compile all of the 5 programs

#Checking that the plaintext files do not have weird characters
dos2unix plaintext1 &>/dev/null
dos2unix plaintext2 &>/dev/null
dos2unix plaintext3 &>/dev/null
dos2unix plaintext4 &>/dev/null
dos2unix plaintext5 &>/dev/null

#Compiling
gcc -o otp_enc_d otp_enc_d.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_dec otp_dec.c
gcc -o keygen keygen.c